export const chatChannelNames = [
    "Altitude Hub",
    "Jetstream Junction",
    "Wingman's Haven",
    "Airborne Plaza",
    "Cloud Nine Chat",
    "Aero Command Center",
    "Hangar Talk",
    "Flight Deck Forum",
    "Propeller Parlor",
    "Mach Speed Meetup",
    "Glide Path Gathering",
    "Nimbus Nest",
    "Horizon Harbor",
    "Tailwind Terrace",
    "SkyClass Pilot Lounge",
    "Altitude Academy",
    "Control Tower Briefing Room",
    "AeroSim Training Hub",
    "Flight Deck Prep Zone",
    "Radar Room Reservoir",
    "Airspace Apprenticeship",
    "Cockpit Classroom",
    "Aviator Ascent Arena",
    "Tower Talk Territory",
    "Vortex Virtuosos Venue",
    "Horizon High Institute",
    "Approach Avenue",
    "Runway Ready Rooms",
    "Clear Skies Symposium",
    "Echo Charlie Center",
    "Windsock Workshop",
    "Vector Visualization Vault",
    "Tailwind Tutorial Terrace",
    "Cabin Crew Collaboration Cove",
    "IFR Insight Inn",
    "VOR Vantage Venue",
    "Nimbus Navigation Nook"
]
